#!/usr/bin/env bash

set -ex
if [ -z ${UNIFI_VERSION+x} ]; then 
    UNIFI_VERSION=$(curl -sX GET https://dl.ui.com/unifi/debian/dists/${UNIFI_BRANCH}/ubiquiti/binary-amd64/Packages \
    | grep -A 7 -m 1 'Package: unifi' \
    | awk -F ': ' '/Version/{print $2;exit}' \
    | awk -F '-' '{print $1}'); \
fi 
curl -L -o /tmp/unifi.deb "https://dl.ui.com/unifi/${UNIFI_VERSION}/unifi_sysvinit_all.deb"
dpkg --force-all -i /tmp/unifi.deb  
rm -f /tmp/unifi.deb 
