#!/bin/bash

DBCOUNT=0
while true; do
    if timeout 1 bash -c "cat < /dev/null > /dev/tcp/${MONGO_HOST}/${MONGO_PORT}" >/dev/null 2>&1; then
        break
    fi
    DBCOUNT=$((DBCOUNT+1))
    echo "*** Defined MONGO_HOST ${MONGO_HOST} is not reachable, attempting again. ***"
    if [[ ${DBCOUNT} -gt 6 ]]; then
        echo "*** Defined MONGO_HOST ${MONGO_HOST} is not reachable, cannot proceed. ***"
        sleep infinity
    fi
    sleep 5
done